export const auth_constant = {
	BASE_PATH: 'auth',
	ERROR_REDIRECT: 'ERROR_REDIRECT',
	USER_IS_NOT_A_ORGANIZER: 'USER_IS_NOT_A_ORGANIZER',
	PASSWORD_NOT_MATCH_REQUIREMENT: 'PASSWORD_NOT_MATCH_REQUIREMENT',
};
