export const userError = {
	USER_NOT_FOUND: 'USER_NOT_FOUND',
	WRONG_PASSWORD: 'WRONG_PASSWORD',
	EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
	USER_IS_RESTRICTED: 'USER_IS_RESTRICTED',
	EMAIL_IS_EXISTS: 'EMAIL_IS_EXISTS',
	TOKEN_IS_NOT_CORRECT: 'TOKEN_IS_NOT_CORRECT',
	USER_VERIFIED: 'USER_VERIFIED',
	TWO_PASSWORDS_DO_NOT_MATCH: 'TWO_PASSWORDS_DO_NOT_MATCH',
};
